### ISSUE TITLE
Infografía - Irving Zárate Reyes 

### ISSUE THREAD

**Issue by Irvingzr16** [SistemasTecTlaxiaco/actividad-1-infografia-Irvingzr16#2]
[Infografía - Irving Zárate Reyes .pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Irvingzr16/files/12481158/Infografia.-.Irving.Zarate.Reyes.pdf)

**Comment by DaisyOrtiz2** [comment]
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
